name: Test Terraform changes

on: 
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
        type: string
      AZURE_TENANT_ID:
        required: true
        type: string
      AZURE_SUBSCRIPTION_ID:
        required: true
        type: string
      STORAGE_ACCOUNT:
        required: true
        type: string
      CONTAINER_NAME:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string
      RESOURCE_GROUP:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  test-terraform:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP" -backend-config="key=app.terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate
